### ISSUE TITLE
crossval_o2m_adjR2 error

### ISSUE THREAD

**Issue by guokai8** [selbouhaddani/O2PLS#2]
Here are still some problems. When I use the function crossval_o2m_adjR2 or crossval_o2m, it reports as shown below

```
crossval_o2m(rna_e,pro_e, a = 1:2, ax = 1:2, ay = 1:2, nr_folds=2)
1: In (function (X, Y, n, nx, ny, stripped = FALSE, p_thresh = 3000,  :
  n + max(nx, ny) = 3 equals sample size
2: In (function (X, Y, n, nx, ny, stripped = FALSE, p_thresh = 3000,  :
  n + max(nx, ny) = 3 equals sample size
3: In loocv_combi(X, Y, e$a, ax[nxny[2]], ay[nxny[1]], app_err = app_err,  :
  Error in (function (X, Y, n, nx, ny, stripped = FALSE, p_thresh = 3000,  : 
  n + max(nx, ny) = 4 exceed sample size N = 3

4: In loocv_combi(X, Y, e$a, ax[nxny[2]], ay[nxny[1]], app_err = app_err,  :
  Error in (function (X, Y, n, nx, ny, stripped = FALSE, p_thresh = 3000,  : 
  n + max(nx, ny) = 4 exceed sample size N = 3
```

So I check the source code of o2m, I found that 

```
if(nrow(X) < n + max(nx, ny)) 
    stop("n + max(nx, ny) = ", n + max(nx, ny), " exceed sample size N = ",nrow(X))
  if(nrow(X) == n + max(nx, ny)) 
    warning("n + max(nx, ny) = ", n + max(nx, ny)," equals sample size")
```

you know my matrix was 6 rows(rna,pro), I use the params in cross_o2m_adjR2 is a=1:2,ax=1:2,ay=1:2, so the max value n+max(nx,ny) was 4, it could not exceed the sample size. If I use o2m function only as shown below

```
fit<-o2m(rna_e,pro_e,2,2,2)
```

it works well. So I think there is something wrong in the cross\* function.

**Comment by selbouhaddani** [comment]
Thanks for making me aware of possible bugs.

The sample size error, I believe, is because you have too few folds. You now fit the model on 6-6/2=3 samples. Try to set `nr_folds = 6`, in this case you fit on 6-6/6 = 5 samples. 
This is also better because the more folds you use, the more accurate the prediction error estimation (the only problem in general is that the computation time increases).

Note also that the `crossval_*` functions do not throw an error, e.g. you can check the errors that were calculated by running `crossval_o2m(...)$Original` for the prediction errors. An `NA` is returned if there was an error for that set of integers.
